language: python
python:
- 3.6
- 3.7
- 3.8
- 3.9
install:
- pip install cython pytest
- make compile
- python setup.py develop
script: py.test -vv
branches:
  only:
    - master
notifications:
  email:
    on_failure: always
    on_success: never
